### ISSUE TITLE
URL to tools generatepassword an changepassword

### ISSUE THREAD

**Issue by beunoit** [bobdenotter/PasswordProtect#11]
Hi !
Nice extension, exactly what I need !
A little suggestion : when you change your admin url in the general configuration (branding:path:), the two links to acces to the tools "_generatepassword_" an "_changepassword_" are broken... You have to change them manually in the address bar to access to the page (/**youradmin**/protect/generatepasswords).
Maybe, we can have access to the branding defined in config.yml path in the _registerMenuEntries()_ function to have directly the good link ?
Best regards,
Benoît

**Comment by bobdenotter** [comment]
Hi, 

In the 3.x version this is handled automatically. Thanks!
