### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mstys** [bobdenotter/PasswordProtect#12]
Hi, I'm getting following error during installation PasswordProtect.

**PHP Error**
```
Could not parse version constraint : Invalid version string ""
File: /vendor/composer/semver/src/VersionParser.php::485
```
Bolt 3.2

Is it possible to fix it or installing extension in another way?

**Comment by bobdenotter** [comment]
I've just tagged v 3.0.3, which should work again on Bolt 3.2.x. Feel free to re-open if issues persist. :-)
