### ISSUE TITLE
BUG : don't redirects when OK

### ISSUE THREAD

**Issue by brethymnis** [bobdenotter/PasswordProtect#13]
Nothing happen when the password is OK, it doesn't redirect. (session nor registered)
But when the password is false, it displays "wrong password"

Works with Bolt 2.2.23 and Password Protect 1.2.0
But not with Bolt 3.2.2 and Password Protect 2.0.0

[phpinfo.pdf](https://github.com/bolt/PasswordProtect/files/633397/phpinfo.pdf)

**Comment by mrenigma** [comment]
I'm having the same issue, also using PHP 7 and FPM-CGI. Looking through the Symfony session method signatures I came across `save()` which makes this work.

Locally I've set `$this->app['session']->save();` after the set/remove of the session values:

```php
$this->app['session']->set('passwordprotect', 1);
$this->app['session']->set('passwordprotect_name', $this->app['passwordprotect.handler.checker']->checkLogin($data));
$this->app['session']->save();
```

```php
$this->app['session']->remove('passwordprotect');
$this->app['session']->remove('passwordprotect_name');
$this->app['session']->save();
```

@bobdenotter I'm happy to do a pull request for this if you don't see any issues with my solution?

**Comment by mrenigma** [comment]
Additionally it's worth saying that when xdebugging this I found the session is set but upon redirect through `RedirectResponse` the session values aren't kept during the transition. Logging into bolt and other session related stuff in bolt works fine.

**Comment by doup** [comment]
I'm not sure if this is related, but I'm having an issue with `v2.0` where I've to login correctly twice to actually login AND once logged it doesnt redirect to the `returnto` URL. Also, once logged I've to refresh the page so that the session is updated…

Anyway, maybe all these issues are already fixed in more recent versions but I can't try it because of #18.

**Comment by bobdenotter** [comment]
I've just tagged v 3.0.3, which should have a fix for this. Feel free to re-open if issues persist. :-)
