### ISSUE TITLE
Installtion Failure + "twig.sandbox.policy" is not defined error

### ISSUE THREAD

**Issue by apewave** [bobdenotter/PasswordProtect#18]
Hi,

I've been trying to install this extension on a fresh installation of Bolt 3.2.9 (on which other extensions install normally).

On installation, I get the error message: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

And the whole site (i.e. all pages) now throws the following error: "twig.sandbox.policy" is not defined.

  [InvalidArgumentException]
  Identifier "twig.sandbox.policy" is not defined.

Exception trace:
 () at /vendor/pimple/pimple/lib/Pimple.php:187
 Pimple->extend() at /extensions/vendor/bobdenotter/passwordprotect/src/PasswordProtectExtension.php:41
 Bolt\Extension\Bolt\PasswordProtect\PasswordProtectExtension->registerServices() at /vendor/bolt/bolt/src/Extension/SimpleExtension.php:39
 Bolt\Extension\SimpleExtension->register() at /vendor/silex/silex/src/Silex/Application.php:178
 Silex\Application->register() at /vendor/bolt/bolt/src/Extension/Manager.php:196
 Bolt\Extension\Manager->register() at /vendor/bolt/bolt/src/Application.php:275
 Bolt\Application->initExtensions() at /vendor/bolt/bolt/src/Application.php:140
 Bolt\Application->initialize() at /vendor/bolt/bolt/app/bootstrap.php:136
 Bolt\{closure}() at n/a:n/a
 call_user_func() at /vendor/bolt/bolt/app/bootstrap.php:140
 require() at /vendor/bolt/bolt/app/nut:14

**Comment by doup** [comment]
Same here, using Bolt `3.2.7`.

**Comment by bobdenotter** [comment]
A ton of work is being done on this extension, but the release of the next version is probably going to coincide with the release of Bolt 3.3.

**Comment by bobdenotter** [comment]
I've just tagged v 3.0.3, which should work again on Bolt 3.2.x. Feel free to re-open if issues persist. :-)
